version: 2.1

# Reused strings
working_directory: &working_directory "/tmp/workspace"

executors:
  node:
    docker:
      - image: circleci/node:10.16
        environment:
          API_URL: https://circleci.com/api/v1.1/project/github/ericmacfa/circleci-playground
    working_directory: *working_directory

# commands:
#   create_and_store:
#     description: "A test command"
#     parameters:
#       store_path:
#         type: string
#     steps:
#       - run: echo "store_path-->'<< parameters.store_path >>'"
#       - run:
#           name: Create File
#           command: node -pe '`${process.env.CIRCLE_PROJECT_REPONAME}-${process.env.CIRCLE_WORKFLOW_ID}-${new Date().toISOString()}`' > << parameters.store_path >>

jobs:
  create:
    executor: node
    steps:
      - checkout
      - run:
          name: Create File
          command: |
            node -pe '`${process.env.CIRCLE_PROJECT_REPONAME}-${process.env.CIRCLE_WORKFLOW_ID}-${new Date().toISOString()}`' > ./artifact.txt
            cat ./artifact.txt
      - store_artifacts:
          path: ./artifact.txt
  list:
    executor: node
    steps:
      - checkout
      - run: curl "$API_URL/latest/artifacts?circle-token=$API_TOKEN&branch=master&filter=completed"
  show:
    executor: node
    steps:
      - checkout
      - run: curl -o ./data "$API_URL/latest/artifacts?circle-token=$API_TOKEN&branch=master&filter=completed"
      - run: cat ./data
      - run: cat ./data | grep -o 'https://[^"]*' | tr -d \" | sed -e "s/$/?circle-token=$CIRCLE_TOKEN/" | wget -v -i -

workflows:
  version: 2
  build:
    jobs:
      - create
      - list:
          requires:
            - create
      - show:
          requires:
            - list
